site_name: FOSIA Documentation

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
markdown_extensions:
  - admonition
nav:
  - Home: index.md

  - Getting Started:
      - Overview: getting-started/index.md
      - Installation: getting-started/installation.md

  - User Guide:
      - Overview: user-guide/index.md
      - Configuration: user-guide/configuration.md
      - Commands: user-guide/commands.md

  - Developer Guide:
      - Overview: developer-guide/index.md
      - Architecture: developer-guide/architecture.md
      - Core: developer-guide/core.md
      - Client: developer-guide/client.md
      - Server: developer-guide/server.md

  - Technical:
     - Overview: technical/index.md

     - Architecture:
         - Overview: technical/architecture/index.md
         - System Architecture: technical/architecture/system.md
         - Data Flow: technical/architecture/data-flow.md

     - Client:
         - Overview: technical/client/index.md
         - Microphone: technical/client/microphone.md
         - Wake Word Detection: technical/client/wwd.md
         - Signaling: technical/client/signaling.md
         - WebRTC: technical/client/webrtc.md

     - Server:
         - Overview: technical/server/index.md
         - Signaling: technical/server/signaling.md
         - WebRTC: technical/server/webrtc.md
         - Audio Queue: technical/server/audio-queue.md
         - Speech-to-Text: technical/server/stt.md

     - Error Handling:
         - Overview: technical/error-handling/index.md

     - Testing:
         - Overview: technical/testing/index.md

     